# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               JerryWang
tagline:             'web developer'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              jerryfwang
  email:             jerryfwang1204@gmail.com

# Custom vars
version:             1.0.0
